version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.24
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      - elasticsearch

  mongodb:
    image: mongo:6
    container_name: mongodb
    command: ["mongod", "--config", "/etc/mongod.conf"]
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db
      - mongo-logs:/var/log/mongodb
    ports:
      - "27017:27017"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.24
    container_name: filebeat
    user: root
    depends_on:
      - elasticsearch
      - kibana
      - mongodb
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - setup.kibana.host=kibana:5601
    command: ["--strict.perms=false"]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - mongo-logs:/var/log/mongodb:ro

volumes:
  es-data:
  mongo-data:
  mongo-logs: